### PR TITLE
AW-131: Shapes with transparent boards do not render correctly

### PR DESCRIPTION
**Pull request by k1w1**
Treat a transparent border the same as having no border. This places the control points at the edge of the rendered fill rather than half the strokeWidth away.

### CODE REVIEW

**Comment by jsteel** [comment]
When you switch between transparent and non, the control points are in the wrong location until you refresh the page.

Screenshot 2024-10-22 at 12 11 46 PM

**Comment by k1w1** [comment]
I think the bug causing this is in https://github.com/aha-app/aha-app/pull/35339 rather than fabric.

**Review by gregplaysguitar — COMMENTED** [review]
There seems to be a ton of indentation/whitespace changes in this PR - can we not change that? It makes it hard to see what's actually changed, and will make it much harder to reconcile this fork with main if we ever want to do that

**Comment by k1w1** [comment]
This version of the PR had whitespace changes. I opened a new version without the whitespace changes.

**Pull request closed without merging**
